class Dashboard {
  int totalUsers;
  int student;
  int parent;
  int management;
  int totalFather;
  int totalMother;
  int totalGuardian;
  int totalAdmin;
  int totalManagement;
  int totalTeachingStaff;
  int totalNonTeachingStaff;
  int totalInstalledFather;
  int totalInstalledMother;
  int totalInstalledGuardian;
  int totalInstalledAdmin;
  int totalInstalledManagement;
  int totalInstalledTeaching;
  int totalInstalledNonteaching;
  int inactiveUser;
  String schoolName;
  int deActiveUserCount;

  Dashboard(
      {required this.totalUsers,
      required this.student,
      required this.parent,
      required this.management,
      required this.totalFather,
      required this.totalMother,
      required this.totalGuardian,
      required this.totalAdmin,
      required this.totalManagement,
      required this.totalTeachingStaff,
      required this.totalNonTeachingStaff,
      required this.totalInstalledFather,
      required this.totalInstalledMother,
      required this.totalInstalledGuardian,
      required this.totalInstalledAdmin,
      required this.totalInstalledManagement,
      required this.totalInstalledTeaching,
      required this.totalInstalledNonteaching,
      required this.inactiveUser,
      required this.schoolName,
      required this.deActiveUserCount});

  factory Dashboard.fromJson(Map<String, dynamic> json) => Dashboard(
      totalUsers: json["total_users"],
      student: json["student"],
      parent: json["parent"],
      management: json["management"],
      totalFather: json["total_father"],
      totalMother: json["total_mother"],
      totalGuardian: json["total_guardian"],
      totalAdmin: json["total_admin"],
      totalManagement: json["total_management"],
      totalTeachingStaff: json["total_teaching_staff"],
      totalNonTeachingStaff: json["total_non_teaching_staff"],
      totalInstalledFather: json["total_installed_father"],
      totalInstalledMother: json["total_installed_mother"],
      totalInstalledGuardian: json["total_installed_guardian"],
      totalInstalledAdmin: json["total_installed_admin"],
      totalInstalledManagement: json["total_installed_management"],
      totalInstalledTeaching: json["total_installed_teaching"],
      totalInstalledNonteaching: json["total_installed_nonteaching"],
      inactiveUser: json["inactive_user"],
      schoolName: json["school_name"],
      deActiveUserCount: json['deactiveusercount']);
}
